dependencies:
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.2871
- alias: jacoco
  name: ext-jacoco
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.77
- name: jx-app-grafana
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.6
